inventory:
  kitEditor:
    title: "Editor de Kit"
    items:
      panel: "type:BLUE_STAINED_GLASS_PANE,display-name:&7"
      claim-time: "type:CLOCK,display-name:&fCambiar el tiempo de reclamación"
      items: "type:CHEST,display-name:&fModificar Objetos"
      close: "type:IRON_DOOR,display-name:&cCerrar Menú"
  itemsEditor:
    title: "Editor de Items"
    items:
      panel: "type:BLUE_STAINED_GLASS_PANE,display-name:&7"
      save: "type:GREEN_WOOL,display-name:&cGuardar"
      cancel: "type:RED_WOOL,display-name:&cCancelar"
