main: org.kayteam.harimelteconomy.HarimeltEconomy
name: HarimeltEconomy
version: 1.0
author: SirOswaldo
depend: [Vault]
softdepend:
  - PlaceholderAPI

commands:
  Economy:
    description: "Manage users balance"
  Balance:
    description: "See your balance and others players balance"
  Pay:
    description: "Pay others players"

permissions:
  HarimeltEconomy.Economy:
    default: op
  HarimeltEconomy.Economy.Give:
    default: op
  HarimeltEconomy.Economy.Take:
    default: op
  HarimeltEconomy.Economy.Set:
    default: op
  HarimeltEconomy.Balance:
    description: "See your balance"
  HarimeltEconomy.Balance.Others:
    description: "See others players balance"