# Storages Available: YAML, MYSQL
storage: YAML
mysql:
  ip: ""
  port: ""
  username: ""
  password: ""
  database: ""
  table: ""
tags:
  wolf:
    prefix: "&7Wolf"
    suffix: ""
  fox:
    prefix: "&5Fox"
    suffix: ""
  turtle:
    prefix: "&aTurtle"
    suffix: ""
